name: Update Gist With WakaTime Stats

on:
  push:
    branches: master

  schedule:
    - cron: "0 */2 * * *"

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        run: npm ci
      - name: Update gist
        run: node ./dist/index.js
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: cb776a9c2f34936636371fe979440656
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
